### PR TITLE
Make the static version work again

### PR DESCRIPTION
**Pull request by nlehuby**
this adds some scripts to scrap the API and have the static version fully working

### CODE REVIEW

**Comment by nlehuby** [comment]
Does somebody want to make a review ?

**Comment by frodrigo** [comment]
Not tested. But the diff look good for me.

**Comment by prhod** [comment]
Hello, if you can give me a few more days, i'd like to test it. Sorry for the delay :-/

**Comment by prhod** [comment]
tested and all green ^^, thanks :+1:

**Pull request merged**
