### PR TITLE
Use accurate distance computation to avoid negative distance issue #37

### PR DESCRIPTION
**Pull request by frodrigo**

### CODE REVIEW

**Comment by prhod** [comment]
I don't have the previous error anymode ! :+1: 
Running the script against France again, I had this new one : 
`psql:/mapping/post-process-display.sql:97: ERROR:  getPoint4d_p: point offset out of range`
I'll try to search why, but if you have an idea ...

For info, I also have this warning : 
`psql:/mapping/post-process-internal.sql:40: WARNING:  ST_Distance_Spheroid signature was deprecated in 2.2.0. Please use ST_DistanceSpheroid`

**Comment by frodrigo** [comment]
Probably an accuracy issue with
```sql
ST_LineInterpolatePoint(i_ways.geom, ST_LineLocatePoint(i_ways.geom, i_positions.geom))
```
Again, please, can you try to locate the object with the issue.

**Comment by prhod** [comment]
I had trouble to isolate the error !  i_routes.osm_id = -2789216
Is it sufficient ?
```sql
SELECT
  array_agg(DISTINCT osm_id) AS rels_osm_id,
  geom
FROM (
  SELECT 
    i_routes.osm_id,
    ST_LineInterpolatePoint(i_ways.geom, ST_LineLocatePoint(i_ways.geom, i_positions.geom)) AS geom
  FROM
    i_routes
    JOIN i_ways ON
      i_routes.osm_id = i_ways.rel_osm_id
    JOIN i_positions ON
      i_routes.osm_id = i_positions.rel_osm_id
    LEFT JOIN i_stops ON
      i_positions.member_type = i_stops.osm_type AND
      i_positions.member_osm_id = i_stops.osm_id
  WHERE
    ST_Distance(
      ST_Transform(i_positions.geom, 4326),
      ST_Transform(ST_LineInterpolatePoint(i_ways.geom, ST_LineLocatePoint(i_ways.geom, i_positions.geom)), 4326)
    ) < 20
    and i_routes.osm_id = -2789216
  ORDER BY
    i_routes.osm_id,
    coalesce(i_stops.name, i_positions.member_type::text || '_' || i_positions.member_osm_id::text)
  ) AS t
GROUP BY
  geom
```

**Comment by frodrigo** [comment]
This last issue is linked with this relation https://www.openstreetmap.org/relation/3109368 as stop.

**Comment by frodrigo** [comment]
Fix the warring and the last issue.

**Pull request merged**
