### PR TITLE
New project directory layout

### PR DESCRIPTION
**Pull request by frodrigo**
Open to comments.

```
.
├── demo.gif
├── docker-compose.yml
├── docker-postgres-env
├── Makefile
├── README.md
├── imposm
│   ├── import
│   ├── post-process-display.sql
│   ├── post-process-internal.sql
│   ├── run_importer.sh
│   └── vapourtrail_mapping.yml
├── t-rex
│   ├── cache
│   ├── generate_all_tiles.sh
│   └── trex.toml
├── vapour_api
│   ├── api.py
│   ├── Dockerfile
│   └── __init__.py
└── web
    ├── glstyle.json
    ├── img
    │   ├── bench.svg
    │   ├── bus.svg
    │   ├── departures.svg
    │   ├── junglebus_vapourtrail_header.png
    │   ├── osm.svg
    │   ├── shelter.svg
    │   ├── tactile.svg
    │   └── wheelchair.svg
    ├── index.js
    ├── layers.js
    ├── modules.js
    ├── prepare_static.sh
    ├── vapour-style.json
    └── vapour_trail.html
```

I'm not comfortable with the `web/prepare_static.sh` script. But should be solved by the merge of vapour_api and web. I can to it too.

### CODE REVIEW

**Comment by prhod** [comment]
Yes, I'm totally in favor for this :+1: (so much better)
I've checked and the only thing I thought was a minor inconsistency in `vapour_api` and `web` folder name. 
With the fixed layout, what would you think of renaming `vapour_api` in `api` ? 
As for the `prepare_static.sh` issue, if we wait for the merge of the web part, maybe can we remove this file ?

**Comment by nlehuby** [comment]
:+1: 
I'm also in favor of `api`. Maybe just `frontend` when we'll merge `web` and  `api`

**Comment by nlehuby** [comment]
what about 
* data
* tiles
* api

instead of using applications names ?

**Comment by frodrigo** [comment]
> I've checked and the only thing I thought was a minor inconsistency in vapour_api and web folder name.

I idea is to merge into
```
. web
-- api (the pyhton API app)
-- public (with web static file, the actual web directory)
-- prepare_static.sh
```

**Comment by frodrigo** [comment]
> 
>    data
>    tiles
>    api
>
>instead of using applications names ?

I think is more about the process (the application) than the result (the osm data in database and the tiles, more, data is too generic for me).

**Comment by prhod** [comment]
Everyone seems to have different ideas. To avoid a long debate, what about keeping initial proposal with only a rename of `vapour_api` in `api` ?

**Comment by frodrigo** [comment]
Yes we can at least do that.

**Comment by prhod** [comment]
thanks for the change, let's wait for @nlehuby to check if everyone's ok with that.

**Comment by frodrigo** [comment]
Updated with last master.

**Pull request merged**
