### PR TITLE
Fixing travis CI

### PR DESCRIPTION
**Pull request by prhod**

### CODE REVIEW

**Comment by prhod** [comment]
Sorry for the spam, I had hard time with this one !
T-rex seems to have changed the static time generation with a "security" on low level tiles. I ended using a 11 level tile on monaco. Not perfect, but sufficient I think.

**Comment by prhod** [comment]
finally, I ended removing the cleanup of empty tiles. Should not be an issue I think.

**Comment by frodrigo** [comment]
t-rex-tileserver/t-rex#94

**Comment by frodrigo** [comment]
Originally t-rex store a lot of pseudo empty tiles. Was bad to on file system and to commit and deploy.
https://github.com/t-rex-tileserver/t-rex/blob/master/CHANGELOG.md#090-2018-07-24

**Comment by prhod** [comment]
thanks @frodrigo !

**Comment by frodrigo** [comment]
Note, I prepare an other commit for other changes about new t-rex.

**Pull request merged**
